// Challenge: simplify and complete the following code.  The robot must move in a square.
Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Forward, 20)
basic.pause(1000)
Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Right, 20)
basic.pause(1200)
Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Forward, 20)
basic.pause(1000)
Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Right, 20)
basic.pause(1200)
Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Forward, 20)
basic.pause(1000)
Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Right, 20)
basic.pause(1200)
Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Forward, 20)
basic.pause(1000)
Kitronik_Move_Motor.move(Kitronik_Move_Motor.DriveDirections.Right, 20)
basic.pause(1200)
Kitronik_Move_Motor.stop()
